language: python

sudo: false

python:
  - 2.7
  - 2.6

os:
  - linux

cache:
  pip: true
  directories:
    - /home/travis/miniconda

addons:
  apt:
    packages:
      - libimage-exiftool-perl
      - libav-tools
      - ffmpeg

before_install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Download and install conda if necessary
  - if ! ( conda -V && which conda ); then
      if [[ "$TRAVIS_PYTHON_VERSION" == "2."* ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi ;
      bash miniconda.sh -f -b -p $HOME/miniconda;
    fi
  # Setup conda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Create and activate the virtualenv
  - if [ ! -e $HOME/miniconda/envs/py$TRAVIS_PYTHON_VERSION ]; then
      conda create -q -n py$TRAVIS_PYTHON_VERSION python=$TRAVIS_PYTHON_VERSION pip;
    fi
  - source activate py$TRAVIS_PYTHON_VERSION
  - if [[ "$(python --version 2>&1)" != *"$TRAVIS_PYTHON_VERSION"* ]]; then exit 1; fi

  # If the branch is "bulk" run bulk tests. This is a special case.
  - if [[ "$TRAVIS_BRANCH" == "bulk" && "$TRAVIS_PYTHON_VERSION" == "2.7" ]] ; then
      export BULK_TEST=true ;
    fi

install:
  - conda update setuptools  # conda has an issue with pip updating setuptools - https://github.com/ContinuumIO/anaconda-issues/issues/542
  - conda install -c conda-forge opencv
  - if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]]; then
      conda install -c menpo dlib;
    fi
  - pip install --ignore-installed -U setuptools  # conda has an issue with pip updating setuptools - https://github.com/ContinuumIO/anaconda-issues/issues/542
  - pip install -r requirements.txt -r test-requirements.txt
  - if [[ "$BULK_TEST" == true ]] ; then
      pip install git+https://github.com/wikimedia/pywikibot-core.git ;
      cp .ci/user-config.py . ;
    fi

script:
  - flake8 setup.py file_metadata tests
  - if [[ "$BULK_TEST" == true ]] ; then
      python -m pytest -k "bulk_test $EXTRA_PYTEST_KEYWORDS" -vvv --capture=no --cov ;
    else
      python -m pytest -k "not bulk_test $EXTRA_PYTEST_KEYWORDS" --cov ;
    fi

after_script:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - python setup.py sdist
  - pip install .
  - pip uninstall -y file-metadata

notifications:
  email: false
