language: python

sudo: false

python:
  # - '3.5'
  # - '3.4'
  # - '3.3'
  - '2.7'
  - '2.6'

os:
  - linux

cache:
  pip: true
  directories:
    # - /home/travis/virtualenv/python3.5/
    # - /home/travis/virtualenv/python3.4/
    # - /home/travis/virtualenv/python3.3/
    - /home/travis/virtualenv/python2.7/
    - /home/travis/virtualenv/python2.6/

addons:
  apt:
    packages:
      - libimage-exiftool-perl
      - libav-tools

install:
  - pip install -U pip
  - pip install -r requirements.txt -r test-requirements.txt

script:
  - flake8 setup.py file_metadata tests
  - python -m pytest --cov

after_script:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - python setup.py sdist
  - pip install .

notifications:
  email: false
